networks:
  proznanie_net:
    name: proznanie_net
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - proznanie_net
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"

  fluent-bit:
    image: fluent/fluent-bit:3.2.6
    container_name: fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    environment:
      FLUENT_ELASTICSEARCH_HOST: elasticsearch
      FLUENT_ELASTICSEARCH_PORT: 9200
    networks:
      - proznanie_net
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      NODE_OPTIONS: "--max-old-space-size=512"
    networks:
      - proznanie_net
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"

  ilm_policy:
    build: .
    container_name: ilm_policy
    depends_on:
      - elasticsearch
    networks:
      - proznanie_net
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: "0.1"

volumes:
  esdata:
    driver: local